### ISSUE TITLE
Cannot specify a username in a slack message

### ISSUE THREAD

**Issue by lucj** [resmoio/kubernetes-event-exporter#11]
When defining a slack receiver I'm not able to specify the identifier of a user so that one can be alerted directly.
In the "message" field it seems the @here or @USERNAME are not taken into account, they just appear as simple text once the message is in slack:

Here is a simple exemple of my slack receiver (I'd like each message be sent to the CHANNEL_ID but also to alert the USERNAME user in that channel).
````
    - name: "slack"
      slack:
        token: TOKEN
        channel: "CHANNEL_ID"
        message: "@USERNAME {{ .Message }}"
        fields:
          Reason: "{{ .Reason }}"
          Namespace: "{{ .Namespace }}"
          Kind: "{{ .InvolvedObject.Kind }}"
          Name: "{{ .InvolvedObject.Name }}"
````

In slack the message appears as shown in the following screenshot (the user  is not notified as the @USERNAME appears like regular text instead of a reference towards the user):

![Capture d’écran 2022-08-15 à 10 15 00](https://user-images.githubusercontent.com/182406/184600446-22f44e49-ec54-48a0-861d-e8059c25ee5c.png)

Any idea of what I'm doing wrong ?
