### ISSUE TITLE
Could not push log to ElasticSearch

### ISSUE THREAD

**Issue by khanhnd48** [resmoio/kubernetes-event-exporter#113]
{"level":"debug","msg":"Stopping container event-exporter","namespace":"monitoring","reason":"Killing","involvedObject":"event-exporter-dc7f4ff78-s4p99","time":"2023-07-28T08:59:59Z","message":"Received event"}
{"level":"error","name":"elasticsearch","time":"2023-07-28T09:00:01Z","message":"There is no channel"}

**Comment by mustafaakin** [comment]
Can you please share the whole config (with sensitive parts redacted)?

**Comment by khanhnd48** [comment]
here is my config. I use hostalias in deployment to route ip backend elastic
logLevel: debug
logFormat: json
maxEventAgeSeconds: 10
kubeQPS: 60
kubeBurst: 60
metricsNamePrefix: event_exporter_
route:
  routes:
    - match:
        - receiver: "elasticsearch"
receivers:		  
  - name: "elasticsearch"
    elasticsearch:
      hosts: https://abc.com
      indexFormat: "ntl02-events-{2006-01-02}"
      username: abc
      password: abc
      useEventID: true

**Comment by dpoetzsch** [comment]
I had the same problem today with `loki`.

For me, the `receivers` property was listed below `route`:

```yaml
# WRONG #
route:
  routes:
    - match:
      - receiver: "dump"
      - receiver: "loki"
  receivers:
    - name: "dump"
      stdout: {}
    - name: "loki"
      loki:
        url: "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
```

Here is how it should look like (`receivers` not indented!):

```yaml
route:
  routes:
    - match:
      - receiver: "dump"
      - receiver: "loki"
receivers:
  - name: "dump"
    stdout: {}
  - name: "loki"
    loki:
      url: "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
```

Interestingly, I did not get this error for the `dump` receiver. However the logs just showed an empty json object instead of the correct log message.
