### ISSUE TITLE
Having trouble Identifiying what permissions to give to make events-exporter work?

### ISSUE THREAD

**Issue by Zocatvous** [resmoio/kubernetes-event-exporter#114]
Hey There,

What IAM permissions should I give to a service account that the 'events-exporter' pod will use once deployed?

**Comment by Zocatvous** [comment]
E0731 22:05:52.989265       1 reflector.go:190] src/k8s.io/contrib/fluentd/event-exporter/watchers/watcher.go:55: Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:jakeg:megatron" cannot list resource "events" in API group "" at the cluster scope

Any ideas on how to get my permissions sorted here?

**Comment by fcoeguiguren** [comment]
I started with 
```
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: ["get", "watch", "list"]
  ```
  Then I'm adding each resource that I see failing. Using the * option was frowned by security folks.
