### ISSUE TITLE
Help with loki

### ISSUE THREAD

**Issue by maxtacu** [resmoio/kubernetes-event-exporter#119]
I have the following event-exporter configuration.
```
  config:
    logLevel: error
    logFormat: json
    maxEventAgeSeconds: 30
    kubeQPS: 100
    kubeBurst: 500
    route:
      routes:
        - match:
          - receiver: loki
    receivers:
      - name: "loki"
        loki:
          url: http://loki-write.loki.svc.cluster.local/loki/api/v1/push

```
and it seems that Loki is not receiving anything and the event-exporter is not showing any errors. What is wrong with this config(same as in readme)? Any help appreciated
