### ISSUE TITLE
Not all Kubernetes Events are recorded

### ISSUE THREAD

**Issue by jmos5156** [resmoio/kubernetes-event-exporter#120]
Using the latest Bitnami chart (2.5.1) and the configuration below

```
kubernetes-event-exporter:
  image:
    registry: ghcr.io
    repository: resmoio/kubernetes-event-exporter
    tag: v1.4
  config:
    logLevel: info
    logFormat: json
    maxEventAgeSeconds: 60
    kubeQPS: 100
    kubeBurst: 500
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
          - receiver: "dump"
    receivers:
      - name: "dump"
        stdout: {}
  nodeSelector:
    kubernetes.io/os: linux
    nodetype: worker
```
    
   I can see that not all events are being recorded in the stdout of the pod
   
   
![image](https://github.com/resmoio/kubernetes-event-exporter/assets/34477034/c7ed1efa-e6b0-49bf-aa77-660973c327a1)

I have also tried with the Bitnami default image (v1.4.0) and can see the same results.
Can you advise as to the next steps?
