### ISSUE TITLE
Export to Loki not working

### ISSUE THREAD

**Issue by gomgomshrimp** [resmoio/kubernetes-event-exporter#128]
Hi, I have set up a `webhook` and a `loki` receiver to export events to loki, but neither is working. 
I'm running Loki in `single binary` mode.

The error is as follows.
```bash
{"level":"error","name":"loki-webhook","time":"2023-09-02T03:05:46Z","message":"There is no channel"}

{"level":"error","name":"loki","time":"2023-09-02T03:05:46Z","message":"There is no channel"}
```

Here is my settings.
* `kubernetes-event-exporter`
  * version
    * `ghcr.io/resmoio/kubernetes-event-exporter:v1.4`
    * `docker.io/bitnami/kubernetes-event-exporter:1.4.0-debian-11-r14` 
    * (both are not working)
  * helm chart: `bitnami/kubernetes-event-exporter`
  * helm chart values
    ```yaml
    replicaCount: 1
    
    image:
      registry: ghcr.io
      repository: resmoio/kubernetes-event-exporter
      tag: v1.4
    
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""
    
    service:
      type: ClusterIP
      port: 2112
    
    ## Override the deployment namespace
    namespaceOverride: "ns-observability"
    
    config:
      logLevel: debug
      logFormat: json
      maxEventAgeSeconds: 60
      kubeQPS: 100
      kubeBurst: 500
      route:
        routes:
          - match:
    #          - receiver: "dump"
              - receiver: "loki-webhook"
              - receiver: "loki"
          - drop:
              - namespace: "ns-observability"
        receivers:
    #      - name: "dump"
    #        stdout: {}
          - name: "loki-webhook"
            webhook:
              endpoint: http://tcn-loki.ns-observability.svc.cluster.local:3100/loki/api/v1/push
              headers:
                Content-Type: application/json
                User-Agent: "kube-event-exporter"
              layout:
                streams:
                  - stream:
                      app: kube-api
                      source: event-exporter
                      severity: "{{ .Type }}"
                      reason: "{{ .Reason }}"
                      name: "{{ .InvolvedObject.Name }}"
                      namespace: "{{ .InvolvedObject.Namespace }}"
                      kind: "{{ .InvolvedObject.Kind }}"
                      host: "{{ .Source.Host }}"
                      component: "{{ .Source.Component }}"
                    values:
                      - - "{{ mul .GetTimestampMs 1000000 }}"
                        - "severity={{ .Type }} namespace={{ .InvolvedObject.Namespace }} object={{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }} reason={{ .Reason }} message={{ .Message }}"
          - name: "loki"
            loki:
              streamLabels:
                app: kube-event-exporter
              url: http://tcn-loki.ns-observability.svc.cluster.local:3100/loki/api/v1/push
    
    
    rbac:
      # If true, create & use RBAC resources
      create: true
    
    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    nodeSelector:
      nodegroup: ng-cluster
    
    ```

* `loki service`
  ```bash
  NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)            AGE
  service/loki-gateway       ClusterIP      172.20.115.223   <none>          80/TCP             12h
  service/loki-headless      ClusterIP      None             <none>          3100/TCP           12h
  service/loki-memberlist    ClusterIP      None             <none>          7946/TCP           12h
  service/tcn-loki           ClusterIP      172.20.206.59    <none>          3100/TCP,9095/TCP  12h
  ```
