### ISSUE TITLE
'{{ .field }}' syntax does not seem to work with Loki synk 

### ISSUE THREAD

**Issue by yogeek** [resmoio/kubernetes-event-exporter#134]
In Loki receiver configuration, it does not seem possible to use templated values for stream labels like in other sinks.

For example, in Slack sink we can use the templated fields `{{ .xxx }}`:
```
receivers:
  - name: "slack"
    slack:
      channel: "@{{ .InvolvedObject.Labels.owner }}"
      message: "{{ .Message }}"
      fields:
        namespace: "{{ .Namespace }}"
        reason: "{{ .Reason }}"
        object: "{{ .Namespace }}"
``` 

I tested this config with Loki sink but the `{{ .xxx}}` part is not rendered before sending to loki :
```
receivers:
  - name: "loki"
    loki:
      streamLabels:
         source: event-exporter
         container: event-exporter
         namespace: "{{ .InvolvedObject.Namespace }}" # <<<< this does not work

```

Is it possible to add some of the event fields like the namespace as loki labels please ?

**Comment by yogeek** [comment]
UPDATE : in fact, after some tests, I discovered that the minimal configuration above works well for the [corresponding dashboard](https://grafana.com/grafana/dashboards/17882-kubernetes-event-exporter/)

```
receivers:
      - name: "loki"
        loki:
          url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
          streamLabels:
            source: event-exporter
            container: event-exporter
```

**Comment by virtualb0x** [comment]
@yogeek Hi!

Can you please help me.
I'm deploying [kubernetes-event-exporter](https://github.com/resmoio/kubernetes-event-exporter) via bitnami helm chat with such values:

```
config:
  metricsNamePrefix: 'event_exporter_'
  logLevel: debug
  logFormat: pretty
  kubeQPS: 100
  kubeBurst: 500
  maxEventAgeSeconds: 600
  receivers:
    - name: "loki"
      loki:
        headers:
          Content-Type: application/json
          User-Agent: "kube-event-exporter"
        streamLabels:
          cluster: bdo_k8s_test
          scrape_job: event-exporter
          namespace: "{{ .InvolvedObject.Namespace }}"
        url: http://loki.corp.domain.com/loki/api/v1/push
  route:
    routes:
      - match:
          - receiver: "loki"
```
and I have no corresponding labels in logs. I mean the are staying in such a way:
![image](https://github.com/user-attachments/assets/477c9bec-4b51-4496-82c8-7e6295535d59)


What is your config. Can you plz  show it?
