### ISSUE TITLE
How to get events to Prometheus/Grafana?

### ISSUE THREAD

**Issue by taemon1337** [resmoio/kubernetes-event-exporter#160]
I've installed via Helm Chart with the following `values.yaml`:

```yaml
metrics:
  enabled: true
config:
  logLevel: error
  logFormat: json
  receivers:
    - name: "dump"
      stdout:
        deDot: true
```

so my question is how can I get the events into prometheus?

The metrics exposed are just `events_sent`, `events_discarded`, and the `go` default ones, which makes sense.

There is no `prometheus` dump or way to get events into the metrics.  I get that these are events so maybe they just can't be exported as metrics, but I'm trying to get the Dashboard up and running.

Any help is appreciated :)

**Comment by AeroNotix** [comment]
You'd have to write a prometheus dump, or use the webhook exporter to convert them to a metric in the service which receives the webhooks.

**Comment by vanhoutenbos** [comment]
I use the bitnami chart that has a built in metric & servicemonitor: https://github.com/bitnami/charts/tree/main/bitnami/kubernetes-event-exporter

```yaml
metrics:
  enabled: true 
  serviceMonitor:
    enabled: true
```

But I am running into the same issue, i want to see the 'BackOff: restarting failed container' events in my prometheus environment
