### ISSUE TITLE
build_info missing revision and version

### ISSUE THREAD

**Issue by ben-nelson-nbcuni** [resmoio/kubernetes-event-exporter#176]
The prometheus metric for `build_info` has `unknown` for the revision and version labels on docker.io/bitnami/kubernetes-event-exporter:1.6.1-debian-12-r19:

`build_info{goarch="arm64",goos="linux",goversion="go1.21.9",revision="unknown",version="unknown"} 1`

<img width="837" alt="image" src="https://github.com/resmoio/kubernetes-event-exporter/assets/104170881/aad85a4b-6c96-4658-a229-305894c7a1a5">

**Comment by t3mi** [comment]
You need to set next values for bitnami chart if version is needed in the metrics
```yaml
image:
  registry: ghcr.io
  repository: resmoio/kubernetes-event-exporter
  tag: v1.7
```
