### ISSUE TITLE
Only showing resources from the namespace where exporter is deployed

### ISSUE THREAD

**Issue by nikolaops** [resmoio/kubernetes-event-exporter#191]
Hello,
I can only see the events within the namespace where its exporter deployed (monitoring) and cant see any other event from other namespaces.
Configuration:
```
config:
  logFormat: json
  logLevel: debug
  metricsNamePrefix: event_exporter_
  clusterName: ${eks_cluster}
  receivers:
  - name: loki
    webhook:
      endpoint: http://loki-stack:3100/loki/api/v1/push
      headers:
        Content-Type: application/json
        User-Agent: kube-event-exporter
      layout:
        streams:
        - stream:
            kind: kube-event
            type: '{{ .Type }}'
          values:
          - - '{{ mul .GetTimestampMs 1000000 }}'
            - level={{ lower .Type | replace "normal" "notice" }} namespace={{ .InvolvedObject.Namespace
              }} object={{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }} reason={{
              .Reason }} message={{ quote .Message }}
```
