### ISSUE TITLE
Pass kubeconfig to exporter

### ISSUE THREAD

**Issue by KavishShah09** [resmoio/kubernetes-event-exporter#192]
Is it possible to pass a kubeconfig to the exporter instead of it using in Cluster Config
My current config is:
```yaml
config:
  leaderElection: {}
  logLevel: debug
  logFormat: pretty
  metricsNamePrefix: event_exporter_
  receivers:
    - name: "dump"
      file:
        path: "/dev/stdout"
        layout: {}
    - name: "loki"
      loki:
        url: "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
        streamLabels:
          source: kubernetes-event-exporter
  route:
    routes:
      - match:
          - receiver: "dump"
          - receiver: "loki"
```

I want to pass my kubeconfig from a secret in my cluster
