### ISSUE TITLE
Error message "Event discarded as being older then maxEventAgeSeconds"

### ISSUE THREAD

**Issue by AlexShemeshWix** [resmoio/kubernetes-event-exporter#196]
Hi
Im running version 1.7.
My setup is to dump all incoming events to the disk and ship it to opensearch by fluentbit.
I dont see any CPU load on my pod, no memory usage, no IO heavy usage.
Still i get "Event discarded as being older then maxEventAgeSeconds" all the time when i check logs of the kube-event-exporter pod.
My configuration is 
```
logLevel: info
logFormat: json
maxEventAgeSeconds: 300
route:
  routes:
    - match:
        - receiver: "dump"
receivers:
  - name: "dump"
    file:
      path: "/logs/kube-events.log"
kubeQPS: 100
kubeBurst: 500
```
please advise.
Thanks
