### ISSUE TITLE
Large number of events are missing, the same event can only be received once

### ISSUE THREAD

**Issue by wangjinxiang0522** [resmoio/kubernetes-event-exporter#197]
Hi
Im running version 1.7.

My configuration is
```
config:
  logLevel: debug
  kubeQPS: 100
  kubeBurst: 500
  maxEventAgeSeconds: 600
  metricsNamePrefix: 'event_exporter_'
  logFormat: json
  receivers:
    - name: "dump"
      file:
        path: "/dev/stdout"
        layout:
           message: "{{ .Message }}"
           reason: "{{ .Reason }}"
           type: "{{ .Type }}"
           count: "{{ .Count }}"
           kind: "{{ .InvolvedObject.Kind }}"
           name: "{{ .InvolvedObject.Name }}"
           namespace: "{{ .Namespace }}"
           component: "{{ .Source.Component }}"
           host: "{{ .Source.Host }}"

    - name: "loki"
      loki:
        streamLabels:
          application: kube-api
          container: event-exporter
        url: http://loki-gateway.stage.sprucetec.com/loki/api/v1/push
        tls:
          insecure: true
  route:
    routes:
      - match:
          - receiver: "loki"
          - receiver: "dump"

nodeSelector:
  node-type: monitoring

image:
  registry: reg.sprucetec.com
  repository: monitor/kubernetes-event-exporter
  tag: 1.6.1-debian-12-r16
``` 

I reviewed the source code and found that the [OnUpdate](https://github.com/resmoio/kubernetes-event-exporter/blob/v1.7/pkg/kube/watcher.go) method is not implemented. Is this the reason why the same event can only be received once?
