### ISSUE TITLE
OpenSearch indexing failed due to mapping error

### ISSUE THREAD

**Issue by enp** [resmoio/kubernetes-event-exporter#20]
Tried to run last docker image of exporter with this config:

```
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        opensearch:
          hosts:
            - https://opensearch:9200
          index: kube-events
          username: {{ .Values.opensearch.username }}
          password: {{ .Values.opensearch.password }}
          tls:
            insecureSkipVerify: true
```

Result is:

```
{"level":"error","time":"2022-09-11T15:00:53Z","caller":"/app/pkg/sinks/opensearch.go:139","message":"Indexing failed: {\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"Could not dynamically add mapping for field [app.kubernetes.io/managed-by]. Existing mapping for [involvedObject.labels.app] must be of type object but found [text].\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"Could not dynamically add mapping for field [app.kubernetes.io/managed-by]. Existing mapping for [involvedObject.labels.app] must be of type object but found [text].\"},\"status\":400}"}
```
```
