### ISSUE TITLE
The mechanism authorization does not work when using kafka

### ISSUE THREAD

**Issue by racgase-dev** [resmoio/kubernetes-event-exporter#205]
https://github.com/resmoio/kubernetes-event-exporter/blob/907ce911f7ea8b347aa1a469aaac9c5b56e78dec/pkg/sinks/kafka.go#L39C47-L39C52
when choosing any authorization mechanism
```
      sasl:
        enable: true
        username: "user"
        password: "Pass"
        mechanism: "sha256" # or sha512
```
the default mechanism plain is always used

if you change the line
		Mechanism string `yaml:"mechanism" default:"plain"`
to
		Mechanism string `yaml:"mechanism" default:"sha256"`
authorization with the sha256 mechanism is successful
