### ISSUE TITLE
A lot of mapper_parsing_exception errors during indexing to Opensearch receiver

### ISSUE THREAD

**Issue by leonsery** [resmoio/kubernetes-event-exporter#221]
Trying to index events to Opensearch, getting a lot of errors like:

`ERR Indexing failed: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"object mapping for [involvedObject.labels.app] tried to parse field [app] as object, but found a concrete value"}],"type":"mapper_parsing_exception","reason":"object mapping for [involvedObject.labels.app] tried to parse field [app] as object, but found a concrete value"},"status":400}`

exporter configuration:

```
leaderElection: {}
logFormat: pretty
logLevel: info
receivers:
  - name: "opensearch-monitoring"
    opensearch:
      hosts:
        - http://monitoring-opensearch.monitoring.svc.cluster.local:9200
      index: kube-events
      indexFormat: "kube-events-{2006.01}"
      username: # Optional
      password: # Optional
      cloudID: # Optional
      apiKey: # Optional
      useEventID: true
      deDot: false
      layout: # Optional
route:
  routes:
  - match:
    - receiver: opensearch-monitoring
```

This is Opensearch version:

![Image](https://github.com/user-attachments/assets/761ef54a-1e50-448e-886d-1341c86a16a5)
