### ISSUE TITLE
Loki support  tls insecure_skip_verify: true

### ISSUE THREAD

**Issue by rubentest** [resmoio/kubernetes-event-exporter#222]
I have auto signed certificate on my loki, that is inside of local network.

For promtail for example, I have
```
  clients:
    - url: XXX
      tls_config: 
        insecure_skip_verify: true
      external_labels:
```

It's possible to add similar support for this?

Many thanks
