### ISSUE TITLE
Kafka auth issue with existing image

### ISSUE THREAD

**Issue by albertilagan** [resmoio/kubernetes-event-exporter#224]
I want to preface this by saying that I'm not entirely sure what's wrong with it but with this config
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    metricsNamePrefix: "kubernetes_event_"
    receivers:
      - name: "kafka"
        kafka:
          clientId: "kubernetes"
          topic: "topic.events"
          brokers:
            - "ip1:port"
            - "ip2:port"
            - "ip3:port"
          compressionCodec: "snappy"
          sasl:
            enable: true
            username: "<username>"
            password: "<password>"
            mechanism: "sha256"
    route:
      routes:
        - match:
            - kind: "Pod"
              receiver: "kafka"

```
```
image: ghcr.io/resmoio/kubernetes-event-exporter:latest
```
I'm getting this error
```json
{"level":"fatal","error":"kafka: client has run out of available brokers to talk to","name":"kafka","time":"2025-03-18T17:24:08Z","message":"Cannot initialize sink"}
```

![Image](https://github.com/user-attachments/assets/7ed46bfd-706c-40c0-b85f-fcbef0cead24)

So I tried to fork and hoping to try debug it, but for some reason without doing any changes aside from re-building the image on my fork it works
```
image: ghcr.io/albertilagan/kubernetes-event-exporter:master
```

![Image](https://github.com/user-attachments/assets/f3ee4357-bad2-402a-8db7-b4f7c50ea12a)
