### ISSUE TITLE
Some events seems not watched

### ISSUE THREAD

**Issue by inlinehockey** [resmoio/kubernetes-event-exporter#235]
Hi, 
I set the log level to debug in the config file, but looks some events are to received from exporter side via checking its own log output. Like example:
3m45s       Warning   FailedGetScale                           horizontalpodautoscaler/php-apache                         deployments/scale.apps "php-apache" not found
15m         Warning   InvalidProviderConfig                    secretstore/redash-redash-ext-secrets                      failed to create GCP secretmanager client: unable to generate gcp access token: rpc error: code = NotFound desc = Not found; Gaia id not found for email 
3m57s       Warning   FailedToRetrieveImagePullSecret          pod/redis-xxx-xxxx                                 Unable to retrieve some image pull secrets 

Could you advise why those events are not recevied then therefor not able to inject to ES, thanks.

**Comment by crouth-redge** [comment]
Also seeing this with a few events and we can't seem to identify why:

ingress-nginx spawns a `ProcessServiceSkipped` that is never caught

GKE has a couple as well: `DNSRecordProvisioningSucceeded` and `PresentError`

We're using no filters on our rules:

```
    clusterName: shr-usw1
    leaderElection: {}
    logFormat: pretty
    logLevel: info
    receivers:
    - name: dump
      stdout:
        deDot: false
    route:
      routes:
      - match:
        - receiver: dump
```
