### ISSUE TITLE
Authentication to AWS ElasticSearch with IAM role

### ISSUE THREAD

**Issue by ro-distefano** [resmoio/kubernetes-event-exporter#236]
Hi,

I'm writing you because i have trouble sending data to my ElasticSearch AWS managed resource ( 7.10 version ), i would like to authenticate using IAM role for this aim i have used an IAM role connected to an k8s Service Account and associate this IAM role to the event-exporter deployment but i obtain this error: 

`{"level":"debug","error":"dial tcp <IP-ELASTICSEARCH>:9200: connect: connection timed out","sink":"dump","event":"<EVENT-MESSAGE>"","time":"2025-06-24T14:12:55Z","message":"Cannot send event"}`

I would like to ask you if it is possible to authenticate through IAM role and if so, how?

this is my configuaration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: event-exporter
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    clusterName: sh5dev
    metricsNamePrefix: event_exporter_
    route:
    # Main route
      routes:
      # This route allows dumping all events because it has no fields to match and no drop rules.
      - match:
        - receiver: dump
      #  - receiver: stdout
    receivers:
      #- name: "stdout"
      #  stdout:
      #    deDot: false
      - name: "dump"
        elasticsearch:
          hosts:
            - <ELASTICSEARCH_ENDPOINT>:9200
          index: kube-events
          indexFormat: "kube-events-{2006-01-02}"
          useEventID: true
          deDot: false
```
