### ISSUE TITLE
Pod is in crashloopback state because of config map error

### ISSUE THREAD

**Issue by jyotibhanot** [resmoio/kubernetes-event-exporter#49]
I am trying to deploy this folder in a infra namespace and getting below error :

https://github.com/resmoio/kubernetes-event-exporter/tree/master/deploy

```{"level":"fatal","error":"yaml: invalid map key: map[interface {}]interface {}{\".InvolvedObject.Kind\":interface {}(nil)}","time":"2023-01-09T11:30:02Z","message":"cannot parse config to YAML"}```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: infra
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    maxEventAgeSeconds: 10
    kubeQPS: 60
    kubeBurst: 60
    # namespace: my-namespace-only # Omitting it defaults to all namespaces.
    route:
      # Main route
      routes:
        # This route allows dumping all events because it has no fields to match and no drop rules.
        - match:
            - receiver: "kafka"
        # # This starts another route, drops all the events in *test* namespaces and Normal events
        # # for capturing critical events
        # - drop:
        #     - namespace: "*test*"
        #     - type: "Normal"
        #       minCount: 5
        #       apiVersion: "*beta*"
        #   match:
        #     - receiver: "kafka"
        # # This a final route for user messages
        # - match:
        #     - kind: "Pod|Deployment|ReplicaSet"
        #       receiver: "kafka"
    receivers:
      - name: "kafka"
        kafka:
          clientId: "kubernetes"
          topic: "logs"
          brokers:
            - "kafka:9092"
          compressionCodec: "snappy"
          layout: #optionnal
            kind: {{ .InvolvedObject.Kind }}
            namespace: {{ .InvolvedObject.Namespace }}
            name: {{ .InvolvedObject.Name }}
            reason: {{ .Reason }}
            message: {{ .Message }}
            type: {{ .Type }}
            createdAt: {{ .GetTimestampISO8601 }}
```            
can someone help me to resolve the error.
