### ISSUE TITLE
In the configuration file, how does a route drop multiple namespaces

### ISSUE THREAD

**Issue by aosolao** [resmoio/kubernetes-event-exporter#57]
I tried to drop the namespaces containing test and temp in the name, but it didn't work.

```
    route:
      routes:
        - drop:
            - namespace: "*test*|*temp*"
            - type: "Normal"
          match:
            - kind: "Pod|Deployment"
              receiver: "file"
```

The events of the namespace containing these two keywords is still collected
