### ISSUE TITLE
Events are missing on newer k8s version

### ISSUE THREAD

**Issue by elops-od** [resmoio/kubernetes-event-exporter#68]
hi
try to use helm chart for **kubernetes-event-exporter** from Bitnami version: 2.2.4 with this values
```
resources:
  limits:
     cpu: 400m
     memory: 250Mi
  requests:
     cpu: 100m
     memory: 25Mi

image:
  registry: ghcr.io/resmoio
  repository: kubernetes-event-exporter
  tag: v1.1

config:
  logLevel: trace
  logFormat: json
  maxEventAgeSeconds: 10
  throttlePeriod: 10
  kubeQPS: 60
  kubeBurst: 60
  route:
      match:
          - receiver: "dump"
  receivers:
    - name: "dump"
      elasticsearch:
        hosts:
          - http://elasticsearch-master.logging:9200
        index: new-kube-events
        indexFormat: "new-kube-events-{2006-01-02}"
        useEventID: false
        deDot: false
        tls:
          insecureSkipVerify: true
```
in elastic I can see only 
_**Successfully assigned POD to NODE**_
and that is all, no other events
but in kubernetes-event-exporter I can see all other events

**Comment by shadrus** [comment]
The same problem. I see many events in kubernetes-event-exporter logs, but only small part of them in Kibana.

```  
config:
    logFormat: json
    route:
      # Main route
      routes:
        # This route allows dumping all events because it has no fields to match and no drop rules.
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        elasticsearch:
          hosts:
            - http://elasticsearch-master:9200
          index: kube-events
          # Ca be used optionally for time based indices, accepts Go time formatting directives
          indexFormat: "kube-events-{2006-01-02}"
          # If set to true, it allows updating the same document in ES (might be useful handling count)
          useEventID: false
          # Type should be only used for clusters Version 6 and lower.
          # type: kube-event
          # If set to true, all dots in labels and annotation keys are replaced by underscores. Defaults false
          deDot: false
          tls: # optional, advanced options for tls
            insecureSkipVerify: true # optional, if set to true, the tls cert won't be verified
```
