### ISSUE TITLE
The layout section is not working

### ISSUE THREAD

**Issue by jyotibhanot** [resmoio/kubernetes-event-exporter#69]
I am outputting the logs to kafka but somehow the layout section is not working.

```
config:
  logLevel: debug
  logFormat: json
  receivers:
    - name: "kafka"
      kafka:
        clientId: "kubernetes"
        topic: "event-logs"
        brokers:
          - "localhost:9092"
        layout:
          eventType: "kube-event"
          createdAt: "{{ .GetTimestampMs }}"
          details:
            message: "{{ .Message }}"
            reason: "{{ .Reason }}"
            tip: "{{ .Type }}"
            count: "{{ .Count }}"
            kind: "{{ .InvolvedObject.Kind }}"
            name: "{{ .InvolvedObject.Name }}"
            namespace: "{{ .Namespace }}"
            component: "{{ .Source.Component }}"
            host: "{{ .Source.Host }}"
            labels: "{{ toJson .InvolvedObject.Labels}}"
  route:
    routes:
      - match:
          - receiver: "kafka"
```

I don't see the layout section in kafka. am I doing anything wrong in config? Can someone show how the output will look like

**Comment by noxjonas** [comment]
I encountered something similar. I was trying to use ClusterName (https://github.com/resmoio/kubernetes-event-exporter/pull/3), though wasn't sure how initially. 
I was referencing it wrong, `{{ .clusterName }}` (bad) instead of `{{ .ClusterName }}` (good). 

So I guess the bug here is that when a translation fails, kubernetes-event-exporter omits the field entirely? In my case I only had one field, and I can see based on webhook response that the field was not present in the request.

It would also be useful if the failure to translate was logged somewhere? I had debug logs on, but didn't see any log relating to this failure.

I imagine something similar could be happening in your case

**Comment by jyotibhanot** [comment]
@noxjonas : Hey Jonas, do you mind sharing your config.yaml or values.yaml. Right now I am hardcoding the clustername like

```
        layout:
            eventType: "kube-event"
            clusterName: "test-eks"
            message: "{{ .Message }}"
            reason: "{{ .Reason }}"
            type: "{{ .Type }}"
            count: "{{ .Count }}"
```

also do we have a helm chart for the same?

**Comment by noxjonas** [comment]
I can't share entire config, but the general gist is:
```
config:
  clusterName: "your-cluster-name"

  route:
    routes:
      - match:
          - receiver: "webhook"

  receivers:
    - name: "webhook"
      webhook:
        endpoint:
        layout:
          attachments:
            - color: "danger"
              title: ":red_circle: [ {{ .ClusterName }} ] scary alert"
              fields:
                - title: "Cluster"
                  value: "{{ .ClusterName }}"
                  short: 'Yes'
```
(I'm using webhook for slack message)

as you can see though, `clusterName` is still hardcoded, it's just in a single location. works for me though since I set that single value via terraform

if you don't set `config.clusterName` you can see in exporter's logs that `.ClusterName` is just an empty string. as far as I'm aware, cluster is unaware of its name anyway, so there's no API or something like that to pull the cluster name from
