### ISSUE TITLE
ClusterRole rules are too permissive

### ISSUE THREAD

**Issue by jameshearttech** [resmoio/kubernetes-event-exporter#75]
[role.yaml](https://github.com/resmoio/kubernetes-event-exporter/blob/master/charts/kubernetes-event-exporter/templates/role.yaml)

```yaml
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
{{- end -}}
```

ClusterRole rules are too permissive! The service account does not need to be able to get, watch, list everything (e.g., secrets). The default should include only what is necessary for the software to function (i.e., events).

If we could configure the rules from the values.yaml that would be awesome.
