### ISSUE TITLE
Empty JSONs in /dev/stdout

### ISSUE THREAD

**Issue by tcordeu** [resmoio/kubernetes-event-exporter#90]
Hello, I have deployed the `kube-event-exporter` with mostly default configs:
```yaml
config:
  logLevel: info
  logFormat: json
```
and I am seeing a lot of empty JSON logs in the output:
```
kubectl -n kubernetes-event-exporter logs -f kubernetes-event-exporter-6d7c58d7c4-bwqd8
{"level":"info","name":"dump","type":"*sinks.File","time":"2023-05-23T13:10:42Z","caller":"/bitnami/blacksmith-sandox/kubernetes-event-exporter-1.1.0/src/github.com/opsgenie/kubernetes-event-exporter/pkg/exporter/engine.go:25","message":"Registering sink"}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
...
```
is there a way to avoid this JSONs from being outputted to `/dev/stdout`?

Thanks,
Thomas.

**Comment by mustafaakin** [comment]
There should be at least one route to route events to. I'm not sure why these logs happen. I could not reproduce it.

**Comment by splattner** [comment]
I get the same, my config looks like:

```
    leaderElection: {}
    logFormat: json
    logLevel: info
    receivers:
    - file:
        layout: {}
        path: /dev/stdout
      name: dump
    route:
      routes:
      - match:
        - receiver: dump
```
